// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix'];
    AAlert: typeof import('ant-design-vue/es')['Alert'];
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABadge: typeof import('ant-design-vue/es')['Badge'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    ADrawer: typeof import('ant-design-vue/es')['Drawer'];
    ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
    AForm: typeof import('ant-design-vue/es')['Form'];
    AFormItem: typeof import('ant-design-vue/es')['FormItem'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AList: typeof import('ant-design-vue/es')['List'];
    AListItem: typeof import('ant-design-vue/es')['ListItem'];
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    APopover: typeof import('ant-design-vue/es')['Popover'];
    ARadio: typeof import('ant-design-vue/es')['Radio'];
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup'];
    AResult: typeof import('ant-design-vue/es')['Result'];
    ASelect: typeof import('ant-design-vue/es')['Select'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ASpin: typeof import('ant-design-vue/es')['Spin'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    ASwitch: typeof import('ant-design-vue/es')['Switch'];
    ATabPane: typeof import('ant-design-vue/es')['TabPane'];
    ATabs: typeof import('ant-design-vue/es')['Tabs'];
    ATag: typeof import('ant-design-vue/es')['Tag'];
    ATextarea: typeof import('ant-design-vue/es')['Textarea'];
    ATooltip: typeof import('ant-design-vue/es')['Tooltip'];
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph'];
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText'];
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle'];
    Block: typeof import('./src/components/global-setting/block.vue')['default'];
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default'];
    Chart: typeof import('./src/components/chart/index.vue')['default'];
    Chatroom: typeof import('./src/components/chatroom/index.vue')['default'];
    Footer: typeof import('./src/components/footer/index.vue')['default'];
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default'];
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default'];
    List: typeof import('./src/components/message-box/list.vue')['default'];
    Menu: typeof import('./src/components/menu/index.vue')['default'];
    MessageBox: typeof import('./src/components/message-box/index.vue')['default'];
    Navbar: typeof import('./src/components/navbar/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default'];
    TabItem: typeof import('./src/components/tab-bar/tab-item.vue')['default'];
  }
}

export {};
